# Generated by Django 5.2.1 on 2025-05-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("sobrenome", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=20, unique=True)),
                ("senha", models.CharField(max_length=64)),
            ],
        ),
    ]
