# Generated by Django 5.2.1 on 2025-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="versiculo",
            old_name="titulo",
            new_name="referencia",
        ),
        migrations.RemoveField(
            model_name="versiculo",
            name="tema",
        ),
        migrations.AddField(
            model_name="versiculo",
            name="temas",
            field=models.ManyToManyField(related_name="versiculos", to="home.tema"),
        ),
    ]
